/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Sources */
        get: operations["load_sources_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Map */
        get: operations["load_map_map__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save Map */
        patch: operations["save_map_map__name__patch"];
        trace?: never;
    };
    "/audio/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Audio */
        get: operations["load_audio_audio__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChordEntry */
        ChordEntry: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Chord */
            chord: string;
        };
        /** EnrichedSegment */
        EnrichedSegment: {
            /** Index */
            index: number;
            /**
             * Segment Name
             * @enum {string}
             */
            segment_name: "intro" | "verse" | "pre-chorus" | "chorus" | "bridge" | "inst" | "outro" | "silence" | "interlude" | "ending";
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Duration */
            duration: number;
            /** Bars */
            bars: number;
            /** Downbeats */
            downbeats: number[];
            /** Phrases */
            phrases: number[];
            /** Chords */
            chords: components["schemas"]["ChordEntry"][];
            /** Loudness Db */
            loudness_db: number;
            /** Loudness Db Start */
            loudness_db_start: number;
            /** Loudness Db End */
            loudness_db_end: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeySignature */
        KeySignature: {
            /** Tonic */
            tonic: string;
            /** Mode */
            mode: string;
        };
        /** Meta */
        Meta: {
            /** Audio Hash */
            audio_hash: string;
            /** Generated At */
            generated_at: string;
            /** Map Version */
            map_version: string;
        };
        /** ModelRef */
        ModelRef: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** MusicMap */
        MusicMap: {
            /** Path */
            path: string;
            /** Bpm */
            bpm: number;
            /** Beats Per Bar */
            beats_per_bar: number;
            /** Duration */
            duration: number;
            /** Beats */
            beats: number[];
            /** Bars */
            bars: number[];
            /** Segments */
            segments: components["schemas"]["EnrichedSegment"][];
            sources: components["schemas"]["Sources"];
            meta: components["schemas"]["Meta"];
            key?: components["schemas"]["KeySignature"] | null;
        };
        /** SaveMapRequest */
        SaveMapRequest: {
            /** Segments */
            segments: components["schemas"]["SegmentBoundaryUpdate"][];
        };
        /** SegmentBoundaryUpdate */
        SegmentBoundaryUpdate: {
            /** Index */
            index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** SourceSummary */
        SourceSummary: {
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** Sources */
        Sources: {
            beats: components["schemas"]["ModelRef"];
            chords: components["schemas"]["ModelRef"];
            structure: components["schemas"]["ModelRef"];
            key?: components["schemas"]["ModelRef"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    load_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSummary"][];
                };
            };
        };
    };
    load_map_map__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_map_map__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveMapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicMap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_audio_audio__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
